[package]
name = "mathru_example"
version = "0.0.1"
authors = ["matthias.eiholzer@gmail.com"]
edition = "2018"

[[bin]]
name = "ode_simple"
path = "ode_implicit.rs"

[dependencies.mathru]
path = "../"
default-features = false
features = ["native"]

[dependencies.plotters]
version = "0.2.12"
