
stages:
    - build
    - test
    - deploy

cargo-build:
    stage: build
    image: "rustlang/rust:nightly"
    script:
      - cargo build --verbose


cargo-test:
    stage: test
    needs: ["cargo-build"]
    image: rust:latest
    script:
      - cargo test --verbose


fmt:
    stage: test
    needs: ["cargo-test"]
    image: "rustlang/rust:nightly"
    script:
        - rustup component add rustfmt
        - cargo +nightly fmt -- --check
