
stages:
    - build
    - test
    - deploy

cargo-build-native:
    stage: build
    image: "rustlang/rust:nightly"
    script:
      - cargo build --features native --verbose

cargo-build-blaslapack:
    stage: build
    image: "rustlang/rust:nightly"
    script:
      - cargo build --features blaslapack --verbose


cargo-test-native:
    stage: test
    needs: ["cargo-build-native"]
    image: rust:latest
    script:
      - cargo test --features native --verbose

cargo-test-blaslapack:
    stage: test
    needs: ["cargo-build-blaslapack"]
    image: rust:latest
    script:
      - cargo test --features blaslapack --verbose

fmt:
    stage: test
    needs: ["cargo-build-native"]
    image: "rustlang/rust:nightly"
    script:
        - rustup component add rustfmt
        - cargo +nightly fmt -- --check
