stages:
    - build
    - test
    - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

before_script:
  - apt-get update -yq
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y cmake gfortran
  - cargo --version

build-default:
  stage: build
  image: rust:latest
  script:
    - cargo build

test-default:
    stage: test
    needs: ["build-default"]
    image: rust:latest
    script:
      - cargo test

build-native:
    stage: build
    image: rust:latest
    script:
      - cargo build --no-default-features --features native

test-native:
    stage: test
    needs: ["build-native"]
    image: rust:latest
    script:
      - cargo test --no-default-features --features native

build-openblas:
    stage: build
    image: rust:latest
    script:
      - cargo build --no-default-features --features openblas

test-openblas:
  stage: test
  needs: ["build-openblas"]
  image: rust:latest
  script:
    - cargo test --no-default-features --features openblas

build-netlib:
  stage: build
  image: rust:latest
  script:
    - cargo build --no-default-features --features netlib

test-netlib:
  stage: test
  needs: ["build-netlib"]
  image: rust:latest
  script:
    - cargo test --no-default-features --features netlib

build-intelmkl:
  stage: build
  image: rust:latest
  script:
    - cargo build --no-default-features --features intel-mkl

test-intelmkl:
  stage: test
  needs: ["build-intelmkl"]
  image: rust:latest
  script:
    - cargo test --no-default-features --features intelmkl

