
stages:
    - build
    - test
    - deploy

build-native:
    stage: build
    image: rust:latest
    script:
      - cargo build --features native --verbose

test-native:
    stage: test
    needs: ["build-native"]
    image: rust:latest
    script:
      - cargo test --features native --verbose

fmt:
  stage: test
  needs: ["build-native"]
  image: rust:latest
  script:
      - rustup component add rustfmt
      - cargo fmt -- --check

build-blaslapack:
    stage: build
    image: rust:latest
    script:
      - cargo build --features blaslapack --verbose

test-blaslapack:
    stage: test
    needs: ["build-blaslapack"]
    image: rust:latest
    script:
      - cargo test --features blaslapack --verbose
