include:
    - template: License-Scanning.gitlab-ci.yml

stages:
    - build
    - test

cargo-build:
    stage: build
    image: rust:latest
    script:
      - cargo build --verbose


cargo-test:
    stage: test
    image: rust:latest
    script:
      - cargo test --verbose