include:
  - template: License-Scanning.gitlab-ci.yml

stages:
  - build
  - test

build:
  master:
    only:
        - master@matthiaseiholze/mathru
    stage: build
    image: rust:latest
    script:
      - cargo build --verbose


test:
  master:
    only:
      - master@matthiaseiholze/mathru
    stage: test
    needs: build
    image: rust:latest
    script:
      - cargo test --verbose