
stages:
    - build
    - test
    - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /.cargo
    - target

build-native:
    stage: build
    image: rust:latest
    script:
      - cargo build --features native
      - pwd
      - ls -a
      - ls -a /

test-native:
    stage: test
    needs: ["build-native"]
    image: rust:latest
    script:
      - cargo test --features native


fmt:
  stage: test
  needs: ["build-native"]
  image: rust:latest
  script:
      - rustup component add rustfmt
      - cargo fmt -- --check

build-blaslapack:
    stage: build
    image: rust:latest
    script:
      - cargo build --features blaslapack

#test-blaslapack:
#    stage: test
#    needs: ["build-blaslapack"]
#    image: rust:latest
#    script:
#      - cargo test --features blaslapack


ls-task:
  stage: test
  needs: ["build-native"]
  image: rust:latest
  script:
    - pwd
    - ls -a