[package]
name = "mathru"
version = "0.1.2"
description = "Simple mathematics library written in Rust"
authors = ["Matthias Eiholzer <matthias.eiholzer@gmail.com>"]
exclude = ["literature/*", "tests/*", "backup/*", ".gitignore"]
keywords = ["mathematics", "statistics", "algebra"]
categories = ["science", "algorithms", "data-structures"]
readme = "README.md"
license = "MIT"
license-file = "LICENSE"
repository = "https://gitlab.com/matthiaseiholzer/mathru"

[dependencies]
rand = "0.6"
blas = "0.19"
#openblas-src = "0.5"
lapack = { version = "0.16"}
#lapack-src = { version = "0.2", features = ["openblas"] }

[dependencies.serde]
version =  "1.0"
features = ["derive"]


[dev-dependencies]
serde_json = "1.0"

[features]
default = ["lapack_be"]
lapack_be = []
native = []


