[package]
name = "mathru"
version = "0.0.1"
description = "Simple matthematics library written in Rust"
authors = ["Matthias Eiholzer <matthias.eiholzer@gmail.com>"]
exclude = ["literature/*", "tests/*"]
keywords = ["math", "mathematics", "statistics"]
categories = ["science"]
readme = "README.md"
license = "MIT"
license-file = "LICENCE"
gitlab = { repository = "git@gitlab.com:matthiaseiholzer/mathru.git", branch = "master" }

[dependencies]
#gnuplot = { git = "https://github.com/SiegeLord/RustGnuplot", version="0.0.26" }
rand = "0.5"
