[package]
name = "mathru"
version = "0.1.2"
description = "Simple mathematics library written in Rust"
authors = ["Matthias Eiholzer <matthias.eiholzer@gmail.com>"]
exclude = ["literature/*", "tests/*", "backup/*", ".gitignore"]
keywords = ["mathematics", "statistics", "algebra"]
categories = ["science", "algorithms", "data-structures"]
readme = "README.md"
license = "MIT"
license-file = "LICENSE"
repository = "https://gitlab.com/matthiaseiholzer/mathru"

[features]
default = ["native"]
blaslapack = ["lapack", "blas", "openblas-src"]
native = []

[dependencies]
rand = "0.6"

[dependencies.serde]
version =  "1.0"
features = ["derive"]


[dev-dependencies]
serde_json = "1.0"


[dependencies.lapack]
version = "0.16"
optional = true

[dependencies.blas]
version = "0.16"
optional = true

[dependencies.openblas-src]
version = "0.5"
optional = true




