[package]
name = "mathru"
version = "0.0.4"
description = "Simple mathematics library written in Rust"
authors = ["Matthias Eiholzer <matthias.eiholzer@gmail.com>"]
exclude = ["literature/*", "tests/*, backup/*"]
keywords = ["math", "mathematics", "statistics"]
categories = ["science", "algorithms", "data-structures"]
readme = "README.md"
license = "MIT"
license-file = "LICENSE"
repository = "https://gitlab.com/matthiaseiholzer/mathru"

[dependencies]
#gnuplot = { git = "https://github.com/SiegeLord/RustGnuplot", version="0.0.26" }
rand = "0.5"
