[package]
name = "mathru"
version = "0.0.5"
description = "Simple mathematics library written in Rust"
authors = ["Matthias Eiholzer <matthias.eiholzer@gmail.com>"]
exclude = ["literature/*", "tests/*", "backup/*", ".gitignore"]
keywords = ["math", "mathematics", "statistics"]
categories = ["science", "algorithms", "data-structures"]
readme = "README.md"
license = "MIT"
license-file = "LICENSE"
repository = "https://gitlab.com/matthiaseiholzer/mathru"

[dependencies]
rand = "0.6"
